name: Install Python and check the version in the workflow

on: 
  workflow_dispatch:

jobs:
  python-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: check Python version
        run: python --version
