name: Simple test Workflow

on:
  push:
    branches:
      - main
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: "Hello There, Hi From GitHub Actions!"
