name: Upload Artifact Workflow

on:
  workflow_dispatch:

jobs:
  save-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4
      - name: Create Output file
        run: echo "This file is created with GitHub Actions!" > output.txt
      - name: Upload output-file
        uses: actions/upload-artifact@v4
        with:
          name: workflow-output
          path: output.txt
